### ISSUE TITLE
[Abandoned Plugin] Continuous Print

### ISSUE THREAD

**Issue by willindiana** [OctoPrint/plugins.octoprint.org#1021]
### Which Plugin?

https://plugins.octoprint.org/plugins/continuousprint/

### Link to ticket on plugin's issue tracker confirming abandonment

https://github.com/Zinc-OS/continuousprint/issues/70

### Is there someone open to adopting it?

Primary: @smartin015  Fallback: @willindiana

**Comment by smartin015** [comment]
Some context: I'd previously opened #966, closing after I heard back from @Zinc-OS. But nobody's heard from them in over a month now, and contributions are piling up. I'm still open to adopting this plugin.

**Comment by willindiana** [comment]
I second that sentiment as I have had an open PR since October of last year. https://github.com/Zinc-OS/continuousprint/pull/46. I have been watching Scott respond and patch issues diligently and I trust he is capable of taking over.

**Comment by jneilliii** [comment]
@Zinc-OS I totally understand life happens and other things take priority over plugin development, but it seems you have a couple of people that are willing to help. Would you be up for adding these guys as contributors to your repo or should we consider this abandoned and transfer ownership?

**Comment by arcasoy** [comment]
@jneilliii May I ask what are the next steps in the process? Hoping to see progress soon from those able to contribute.

**Comment by jneilliii** [comment]
Since it appears Zinc-OS has gone the next steps are to create a fork and merge any outstanding PRs/bug fixes and release as a new version on your fork, making sure to update the version in setup.py. Once that is completed submit a PR here adding yourself to the authors list in the template and update the links and such to your fork. We'll then review that PR and verify everything is setup properly to redirect people to your new fork for the new version.

**Comment by jneilliii** [comment]
Here's an example of an adoption PR...

https://github.com/OctoPrint/plugins.octoprint.org/pull/998/files
