### ISSUE TITLE
[Abandoned Plugin] CostEstimation

### ISSUE THREAD

**Issue by Hillshum** [OctoPrint/plugins.octoprint.org#1334]
### Which Plugin?

https://plugins.octoprint.org/plugins/costestimation/

### Link to ticket on plugin's issue tracker confirming abandonment

https://github.com/OllisGit/OctoPrint-CostEstimation/issues/27

### Is there someone open to adopting it?

@hillshum

**Comment by Hillshum** [comment]
Also [my PR for this plugin](https://github.com/OllisGit/OctoPrint-CostEstimation/pull/26) is now going on 3 months with no response.

**Comment by jneilliii** [comment]
Please file a PR for taking over the plugin. It would be similar to the previous one submitted by Olli when he took it over, changes linked below. Bump the version on your fork and create a tag and release that matches that version number. 

https://github.com/OctoPrint/plugins.octoprint.org/pull/630/files

However, instead of `author:` with a comma separated list, you should use `authors:` as a list. 

```
authors:
- Hilton Shumway (or however you want your name to show)
- Olli
- Sven Lohrmann
```
