### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by Neiljclements** [OctoPrint/plugins.octoprint.org#324]
Firstly, it doesn't appear in a search within the plug in manager, so I attempted to install via URL within plug in manager.  However, I get the error as shown in the photo.

![Capture](https://user-images.githubusercontent.com/7466466/58712075-c7738000-83b7-11e9-99f4-40bdd0cf81be.PNG)

**Comment by foosel** [comment]
a) That's the wrong URL, see https://plugins.octoprint.org/plugins/octopod/ for the right one: `https://github.com/gdombiak/OctoPrint-OctoPod/archive/master.zip` 

b) You might have to refresh the plugin list from the repository for it to show up there:

![image](https://user-images.githubusercontent.com/83657/58713603-34d8de00-83c3-11e9-874d-260464b55f30.png)

**Comment by foosel** [comment]
Just tested on a current 1.3.11 instance:

![image](https://user-images.githubusercontent.com/83657/58717478-9ef58100-83cb-11e9-8a05-7b467c37b868.png)

Needs a refresh though, see above. OctoPrint caches the repository data for 24h, unless you have something else configured:

![image](https://user-images.githubusercontent.com/83657/58717563-ccdac580-83cb-11e9-84f8-77fd4f6ce710.png)

**Comment by Neiljclements** [comment]
Thank you very much.  It works perfectly now.  I'm a big fan of OctoPod and I'm sure this will compliment it perfectly.

**Comment by gdombiak** [comment]
FYI @foosel, I'm getting reports that it has been over 48 hours and the plugin does not appear in the local OctoPrint instance. Users have to click on refresh list from repo as mentioned above to make the plugin appear. I have no logs or other info.

**Comment by foosel** [comment]
Hm... I can reproduce this on an instance I haven't touched in several weeks and am very much confused by this. I did not change anything on the server or on the build. 

*sigh* this is going to be fun to figure out

**Comment by foosel** [comment]
Seems to be a bug in OctoPrint's Plugin Manager that's been in there forever. It should refresh the cache on repository requests from the client/browser, but this appears to never have been implemented in that way. See https://github.com/foosel/OctoPrint/issues/3190. Funny that it only now got noticed.

**Comment by gdombiak** [comment]
Thanks @foosel, great detective work!

**Comment by Neiljclements** [comment]
This app is awesome!
Where would be the place to leave suggestions for additions to the app? I’d love to have information like what layer was being printed on the first panel screen and a couple of other ideas.

**Comment by gdombiak** [comment]
Thanks @Neiljclements for the nice words!. Here is the main [git repo for OctoPod](https://github.com/gdombiak/OctoPod) and you can file suggestions directly [here](https://github.com/gdombiak/OctoPod/issues).

Regarding current Z layer, I wanted that feature too when I started OctoPod. I even coded it to later realize that OctoPrint removed support for it since it was not reporting an accurate number. I think that the issue is the Marlin firmware not reporting it so OctoPrint cannot be certain. IIRC, there is a plugin that tried to restore that feature but it was not accurate due to the same reason. If the information is available in OctoPrint then I'd add it in a heartbeat. :)

Thanks,
Gaston
