### ISSUE TITLE
[Listing Error] Bed Level Visualizer

### ISSUE THREAD

**Issue by willdauncey** [OctoPrint/plugins.octoprint.org#611]
Cannot install this plugin for the life of me. Just keeps repeating "Building wheel for numpy (setup.py): still running..." repeatedly until it fails. Running on pi 2B

**Comment by jneilliii** [comment]
This issue tracker is for the plugin repo itself, please open tickets specific to a plugin in it's repo. For your convenience I have linked it below.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/issues

But for the record, since that is my plugin, I am aware of this and yes it takes forever let it run. On a 2B it could take up to an hour to complete.
