### ISSUE TITLE
[Listing Error] DisplayLayerProgress

### ISSUE THREAD

**Issue by Alainjol** [OctoPrint/plugins.octoprint.org#755]
**Which Plugin? (URL to plugin page on plugin repository)**

**What's wrong with the plugin *listing*?**

**Comment by cp2004** [comment]
Please don't open blank issues, fill in all the details so that we know what is wrong.

For problems with the **plugin repository itself** then you can file them here, for problems with **anything else** please make sure you are in the right place.

**Comment by OllisGit** [comment]
Hi @Alainjol,

beside the remarks from cp2002: if you want to report an issue about DLP Version 1.25.2, see [issue 205](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/205)  ...and this is fixed in [Version 1.25.3](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/releases/tag/1.25.3)
