### ISSUE TITLE
[Listing Error] SimplyPrint Cloud

### ISSUE THREAD

**Issue by dkalinai** [OctoPrint/plugins.octoprint.org#763]
The plugin in the subject despite being advertised on the octoprint page is not listed in the repository from Octoprint.

**Comment by cp2004** [comment]
It is? https://plugins.octoprint.org/plugins/SimplyPrint/

You may need to wait for the cache on the repository to expire, since it only refreshes every 24 hours.

Here's a screenshot of the button:
![image](https://user-images.githubusercontent.com/31997505/106664933-9b050380-659d-11eb-82c8-2414493711d3.png)

Click that, then come back here and let us know that it is *hopefully* fixed.

**Comment by dkalinai** [comment]
Got it, that must be the 24h thing. Oh well, sorry to have bothered everyone. I ended up injecting direct install link from the github repo before this reply arrived.
