### ISSUE TITLE
[Listing Error] OctoPrint-WebcamStreamer

### ISSUE THREAD

**Issue by mitchscobell** [OctoPrint/plugins.octoprint.org#784]
**Which Plugin?**

https://plugins.octoprint.org/plugins/webcamstreamer/

**What kind of listing error are you reporting?**

broken link on the listing

Error being thrown when I try and pull the docker image

`
pi@octopi-4:~ $ docker pull adilinden/rpi-stream:latest
Error response from daemon: pull access denied for adilinden/rpi-stream, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
`

**Comment by foosel** [comment]
Was reported to the plugin already:

https://github.com/adilinden-oss/octoprint-webcamstreamer/issues/39

Since we can't guess what would be right here (it's not a broken link per se on the plugin repo's end but rather wrong instructions), I'll have to refer you to the plugin's own issue on this. I've pinged the original author and asked whether the plugin is still being maintained and if so to please fix this. It's now up to the author to do something about it. 

If we don't hear anything back within 14 days, I'll start an abandoned plugin process.
