### ISSUE TITLE
[Listing Error] OctoPrint-Filamentstorage

### ISSUE THREAD

**Issue by paulokinho** [OctoPrint/plugins.octoprint.org#928]
### Which Plugin?

https://plugins.octoprint.org/plugins/filamentstorage/

### What kind of listing error are you reporting?

incorrect compatibility information on the plugin listing

### What specifically is broken or wrong?

It does not work when is installed, not sure why but it seems it is not python 3 compatible.

**Comment by cp2004** [comment]
It is not Python 3 compatible, yes, but that is also listed correctly on the page you linked. So there's no listing error, please report issues to the plugin author at https://github.com/waltmoorhouse/OctoPrint-Filamentstorage

---

Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin repository, not issues with the plugins registered in it:

> What kinds of issues you should report here:
> 
> * missing or broken homepage, source or download URLs
> * broken images
> * incorrect compatibility information
> * ... in short, anything related to the data on plugins.octoprint.org
> 
> What you should not report here:
> 
> * Any kinds of issues with the plugins themselves - report those to the plugin author instead!

Thanks :)
