### ISSUE TITLE
[Listing Error] Octoprint-Chituboard

### ISSUE THREAD

**Issue by marndra** [OctoPrint/plugins.octoprint.org#944]
### Which Plugin?

https://plugins.octoprint.org/plugins/Chituboard/

### What kind of listing error are you reporting?

incorrect compatibility information on the plugin listing

### What specifically is broken or wrong?

installed Octoprint-Chituboard v0.1.3 on my ubuntu 20.04.3 odroid C2 and now octoprint 1.70rc3 can no more boot (instane 1)

I have:
Hardware: Odroid C2 (64GB eccm)
Software: OS ubuntu from hardkernel, updated latest to 20.04.3
Octoprint with 2 virtual instances: first with 1.70rc3 for my tronxy xy3 and second instance geeetech i3pro (octo 1.6)
Instance 2 / Printer: geeetech i3pro with marlin
Instance 1 / printer: tronxy xy3 with chitu 2.0

Everything worked fine until I installed und octoprint instance for tronxy printer via plugin manager the chituboard.
Now the octorpint cannt connect to my configured instance 192.168.1.45:5001
The other worked fine, sure the chite plugin is not needed there (marlin)

How can I uninstall (via SSH) this Chitu plugin???

regards Martin

**Comment by cp2004** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin repository, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
> 
> * missing or broken homepage, source or download URLs
> * broken images
> * incorrect compatibility information
> * ... in short, anything related to the data on plugins.octoprint.org
> 
> What you should not report here:
> 
> * Any kinds of issues with the plugins themselves - report those to the plugin author instead!

If you need support using OctoPrint and plugins, please use the [community forums](https://community.octoprint.org) or the [discord server](https://discord.octoprint.org), as the bug trackers are for *bugs*.
