### ISSUE TITLE
[Listing Error] Bed Level Visualizer

### ISSUE THREAD

**Issue by K20FRITZ** [OctoPrint/plugins.octoprint.org#971]
### Which Plugin?

https://plugins.octoprint.org/plugins/bedlevelvisualizer/

### What kind of listing error are you reporting?

broken images on the listing

### What specifically is broken or wrong?

the visual will not show after the probing. new octo print install new octopi install python3 now 1.7. worked b4 the upgrade

**Comment by cp2004** [comment]
Where is the broken image on that page?

**Comment by K20FRITZ** [comment]
This is all I get.  I clicked the link it shows the box. I Uninstalled it and reinstalled as well. ![16402829283334583784689390108069](https://user-images.githubusercontent.com/59301029/147277554-ddf04bcf-646b-4593-a4d9-0c4286540804.jpg)

**Comment by K20FRITZ** [comment]
![16402831533194810992712005719904](https://user-images.githubusercontent.com/59301029/147277824-3e587a25-c3e5-4d40-b060-197683902781.jpg)

**Comment by cp2004** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin repository, not issues with the plugins registered in it

What kinds of issues you should report here:

* missing or broken homepage, source or download URLs
* broken images
* incorrect compatibility information
* ... in short, anything related to the data on plugins.octoprint.org

What you should not report here:

* Any kinds of issues with the plugins themselves - report those to the plugin author instead!

**Comment by K20FRITZ** [comment]
Sorry My fault.
