### ISSUE TITLE
[Listing Error] Continuous Print

### ISSUE THREAD

**Issue by sidneyns** [OctoPrint/plugins.octoprint.org#973]
### Which Plugin?

https://plugins.octoprint.org/plugins/continuousprint/

### What kind of listing error are you reporting?

a typo in the plugin listing

### What specifically is broken or wrong?

hello

I installed the 24 of december plugin update and the continuous print stop working.. it says initializing and wont start anything

**Comment by jneilliii** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin repository, not issues with the plugins registered in it

What kinds of issues you should report here:

* missing or broken homepage, source or download URLs
* broken images
* incorrect compatibility information
* ... in short, anything related to the data on plugins.octoprint.org

What you should not report here:

* Any kinds of issues with the plugins themselves - report those to the plugin author instead!
